DATA SEGMENT PARA PUBLIC 'DATA'
	STRING DW 2, 10, 20, 40
	LEN DW ($-STRING)/2
DATA ENDS

CODE1 SEGMENT PARA PUBLIC 'CODE'
PROCED PROC FAR
 	ASSUME CS:CODE1, ES:DATA, DS:DATA
 	PUSH DS
 	XOR AX, AX
 	PUSH AX
 	MOV AX, DATA
	MOV DS, AX
	MOV AX, 0
	MOV BX, OFFSET STRING
	MOV CX, LEN
	
	CALL SUM
	
 	RET
PROCED ENDP 				
CODE1 ENDS 				 

CODE2 SEGMENT PARA PUBLIC 'CODE' 
PUBLIC SUM 
PUBLIC

ASSUME CS:CODE2
SUM PROC FAR	
			
	MOV SI, 0
   	L1: 
		MOV DX, [BX+SI]
		ADD AX, DX
		ADD SI, 2
		LOOP L1
		RETF
SUM ENDP
CODE2 ENDS
END PROCED
